export const characters = {
    worker: {
        name: 'Рабочий',
        speed: 3.2,
        acceleration: 3,
        turnSpeed: 3,
        maxSpeed: 4.5,
        skill: 'none',
        color: '#88aaff',
        desc: 'Сбалансированный',
    },
    strong: {
        name: 'Силач',
        speed: 1.8,
        acceleration: 1.2,
        turnSpeed: 1.5,
        maxSpeed: 7.0,
        skill: 'breakSoft',
        color: '#ff8866',
        desc: 'Ломает мягкие стены на скорости >4',
    },
    agile: {
        name: 'Ловкач',
        speed: 3.5,
        acceleration: 4.5,
        turnSpeed: 5,
        maxSpeed: 5.2,
        skill: 'noSlippery',
        color: '#66ff88',
        desc: 'Игнорирует скользкие/липкие полы',
    },
    mage: {
        name: 'Маг',
        speed: 2.2,
        acceleration: 2.2,
        turnSpeed: 2.2,
        maxSpeed: 4.0,
        skill: 'vision',
        color: '#aa88ff',
        desc: 'Видит путь к выходу (мигает)',
    },
};
